### PR TITLE
Passing --size to lvcreate twice results in error

### PR DESCRIPTION
**Pull request by bwerthmann**
While testing a new mount, this error failed a deploy:

```
Fatal error, `/sbin/lvm lvcreate --extents 100%VG --extents 100%VG
--name cluster-object-storage-brick0 gluster-packages-b0-vg ` returned 3
with 'Option -l/--extents may not be repeated.
```

This code path is only hit in the case of `mounts` which are non-ephemeral and non-thin_provision.

Passing size to lvcreate twice results in an error. Size is passed in `common_arguments` as well.

Fixes #ENGT-9252
@vitroth @lilirui @shr3kst3r

### CODE REVIEW

**Comment by bwerthmann** [comment]
Unblocks https://github.com/apcera/continuum-chef/pull/641

**Comment by shr3kst3r** [comment]
LGTM

**Comment by vitroth** [comment]
I'm confused...  I see the error you're fixing, but if that error is fatal how has this code worked at all for the last 9 months?

**Comment by vitroth** [comment]
confusion cleared from discussion w/ Ben...

The only LVM volumes we create via this recipe right now are the gluster thin provisioned volumes.  The other LVM volume is ephemeral and thus created at run-time via the the ephemeral filesystem mechanisms (that I wrote, doh...)

LGTM

**Pull request merged**
